name: Pass Fail Metrics
on:
  schedule:
    - cron: '0 2-14/3 * * 1-5'
  
jobs:
  metrcis-gathering:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - application: ALPHA         
            project: ALPHA  
            testrail-api: https://dashboardnew.testrail.io/index.php?/api/v2
            testrail-user: TESTRAIL_USER
            testrail-key: TESTRAIL_KEY
            jira-api: https://vamsiinduri4455.atlassian.net/rest/api/3
            jira-key: JIRA_API_TOKEN  
                       
            
          - application: BETA         
            project: BETA  
            testrail-api: https://dashboardnew.testrail.io/index.php?/api/v2
            testrail-user: TESTRAIL_USER
            testrail-key: TESTRAIL_KEY
            jira-api: https://vamsiinduri4455.atlassian.net/rest/api/3
            jira-key: JIRA_API_TOKEN
             

          - application: DELTA         
            project: DELTA  
            testrail-api: https://dashboardnew.testrail.io/index.php?/api/v2
            testrail-user: TESTRAIL_USER
            testrail-key: TESTRAIL_KEY
            jira-api: https://vamsiinduri4455.atlassian.net/rest/api/3
            jira-key: JIRA_API_TOKEN
             

          - application: OMICRON         
            project: OMICRON  
            testrail-api: https://dashboardnew.testrail.io/index.php?/api/v2
            testrail-user: TESTRAIL_USER
            testrail-key: TESTRAIL_KEY
            jira-api: https://vamsiinduri4455.atlassian.net/rest/api/3
            jira-key: JIRA_API_TOKEN
            

          - application: ETA         
            project: ETA  
            testrail-api: https://dashboardnew.testrail.io/index.php?/api/v2
            testrail-user: TESTRAIL_USER
            testrail-key: TESTRAIL_KEY
            jira-api: https://vamsiinduri4455.atlassian.net/rest/api/3
            jira-key: JIRA_API_TOKEN  
             
          
            
       

    container:
      image: node:latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run Dash2
        continue-on-error: true
        env:
          APPLICATION: ${{ matrix.application }}
         
          TESTRAIL_API:  ${{ matrix.testrail-api }}
          TESTRAIL_USER: ${{ secrets[matrix.testrail-user] }}
          TESTRAIL_KEY: ${{ secrets[matrix.testrail-key] }}
          PROJECT: ${{ matrix.project }}
          JIRA_KEY: ${{ secrets[matrix.jira-key] }}
          ACTIVE_JIRA_API: ${{ matrix.jira-api }} 
          ACTIVE_JIRA_USER: ${{ secrets[matrix.jira-user] }}

      - name: give some time to publish metrics
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
